[project]
name = "task-stardist"
version = "0.1.1"
description = "Integration of Stardist algorithm as a Cytomine task"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "geojson==3.1.0",
  "imageio==2.34.1",
  "pyyaml==6.0.1",
  "stardist==0.9.1",
]
